import type {
  MacroProgress,
  BudgetTarget,
  MealEntry,
  Restaurant,
  MealRecommendation,
  SmartInsight,
  Achievement,
  WeeklyMealPlanDay,
  YesterdayComparison,
} from '@/types';

export const MOCK_MACROS: MacroProgress = {
  calories: 2200,
  proteinGrams: 150,
  carbsGrams: 220,
  fatGrams: 70,
  consumedCalories: 1450,
  consumedProteinGrams: 92,
  consumedCarbsGrams: 140,
  consumedFatGrams: 48,
};

export const MOCK_BUDGET: BudgetTarget = {
  dailyLimit: 600,
  spent: 340,
  currency: 'INR',
};

export const MOCK_YESTERDAY: YesterdayComparison = {
  calories: 1290,
  proteinGrams: 82,
  budgetSpent: 380,
};

export const MOCK_MEALS: MealEntry[] = [
  {
    id: 'meal-1',
    type: 'breakfast',
    title: 'Greek Yogurt Protein Bowl',
    restaurantName: 'The Green Bowl',
    calories: 380,
    proteinGrams: 32,
    price: 180,
    scheduledAt: '08:00',
    ordered: true,
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&h=200&fit=crop',
  },
  {
    id: 'meal-2',
    type: 'lunch',
    title: 'Grilled Chicken & Quinoa',
    restaurantName: 'MealFit Kitchen',
    calories: 620,
    proteinGrams: 48,
    price: 260,
    scheduledAt: '13:00',
    ordered: true,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200&h=200&fit=crop',
  },
  {
    id: 'meal-3',
    type: 'snack',
    title: 'Roasted Chickpea Trail Mix',
    restaurantName: 'Snack Lab',
    calories: 210,
    proteinGrams: 12,
    price: 90,
    scheduledAt: '16:30',
    ordered: false,
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=200&h=200&fit=crop',
  },
  {
    id: 'meal-4',
    type: 'dinner',
    title: 'Paneer Tikka & Brown Rice',
    restaurantName: 'Tandoori House',
    calories: 590,
    proteinGrams: 34,
    price: 310,
    scheduledAt: '20:00',
    ordered: false,
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=200&h=200&fit=crop',
  },
];

export interface MockDaySummary {
  day: string;
  date: string;
  calories: number;
  targetCalories: number;
  proteinGrams: number;
  spent: number;
  mealsPlanned: number;
  isToday?: boolean;
}

export const MOCK_WEEK: MockDaySummary[] = [
  {
    day: 'Mon',
    date: 'Jun 30',
    calories: 2100,
    targetCalories: 2200,
    proteinGrams: 140,
    spent: 560,
    mealsPlanned: 4,
  },
  {
    day: 'Tue',
    date: 'Jul 1',
    calories: 2250,
    targetCalories: 2200,
    proteinGrams: 155,
    spent: 610,
    mealsPlanned: 4,
  },
  {
    day: 'Wed',
    date: 'Jul 2',
    calories: 1980,
    targetCalories: 2200,
    proteinGrams: 132,
    spent: 480,
    mealsPlanned: 3,
  },
  {
    day: 'Thu',
    date: 'Jul 3',
    calories: 2190,
    targetCalories: 2200,
    proteinGrams: 148,
    spent: 590,
    mealsPlanned: 4,
  },
  {
    day: 'Fri',
    date: 'Jul 4',
    calories: 2320,
    targetCalories: 2200,
    proteinGrams: 160,
    spent: 640,
    mealsPlanned: 4,
  },
  {
    day: 'Sat',
    date: 'Jul 5',
    calories: 1450,
    targetCalories: 2200,
    proteinGrams: 92,
    spent: 340,
    mealsPlanned: 2,
    isToday: true,
  },
  {
    day: 'Sun',
    date: 'Jul 6',
    calories: 0,
    targetCalories: 2200,
    proteinGrams: 0,
    spent: 0,
    mealsPlanned: 0,
  },
];

export const MOCK_HISTORY: MockDaySummary[] = MOCK_WEEK.filter((day) => day.mealsPlanned > 0);

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'The Green Bowl',
    cuisine: 'Healthy · Salads',
    rating: 4.6,
    etaMinutes: 28,
    priceForOne: 220,
    matchReason: 'High protein, fits your calorie budget',
  },
  {
    id: 'rest-2',
    name: 'MealFit Kitchen',
    cuisine: 'Protein Bowls',
    rating: 4.5,
    etaMinutes: 35,
    priceForOne: 260,
    matchReason: 'Best protein-per-rupee match nearby',
  },
  {
    id: 'rest-3',
    name: 'Tandoori House',
    cuisine: 'North Indian',
    rating: 4.3,
    etaMinutes: 40,
    priceForOne: 310,
    matchReason: 'Within budget, hits your dinner macros',
  },
];

export const MOCK_MEAL_RECOMMENDATIONS: MealRecommendation[] = [
  {
    id: 'rec-1',
    name: 'Chicken Burrito Bowl',
    restaurantName: 'Fresh Bowl',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
    rating: 4.7,
    etaMinutes: 20,
    distanceKm: 1.2,
    calories: 620,
    proteinGrams: 48,
    price: 310,
    isVeg: false,
    healthScore: 92,
    tags: ['high-protein'],
  },
  {
    id: 'rec-2',
    name: 'Paneer Tikka Bowl',
    restaurantName: 'The Green Bowl',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    rating: 4.6,
    etaMinutes: 25,
    distanceKm: 0.8,
    calories: 480,
    proteinGrams: 34,
    price: 280,
    isVeg: true,
    healthScore: 88,
    tags: ['under-budget', 'vegetarian'],
  },
  {
    id: 'rec-3',
    name: 'Greek Yogurt Parfait',
    restaurantName: 'Snack Lab',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop',
    rating: 4.5,
    etaMinutes: 15,
    distanceKm: 1.5,
    calories: 320,
    proteinGrams: 28,
    price: 220,
    isVeg: true,
    healthScore: 95,
    tags: ['quick-delivery', 'under-budget', 'vegetarian'],
  },
  {
    id: 'rec-4',
    name: 'Grilled Salmon Plate',
    restaurantName: 'MealFit Kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop',
    rating: 4.8,
    etaMinutes: 30,
    distanceKm: 2.1,
    calories: 540,
    proteinGrams: 42,
    price: 450,
    isVeg: false,
    healthScore: 90,
    tags: ['high-protein'],
  },
  {
    id: 'rec-5',
    name: 'Tofu Rainbow Rice Bowl',
    restaurantName: 'Urban Veg Kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
    rating: 4.4,
    etaMinutes: 18,
    distanceKm: 1.1,
    calories: 410,
    proteinGrams: 30,
    price: 240,
    isVeg: true,
    healthScore: 91,
    tags: ['quick-delivery', 'under-budget', 'vegetarian'],
  },
  {
    id: 'rec-6',
    name: 'Egg White Wrap Combo',
    restaurantName: 'Protein Point',
    imageUrl: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=600&h=400&fit=crop',
    rating: 4.3,
    etaMinutes: 16,
    distanceKm: 0.9,
    calories: 460,
    proteinGrams: 38,
    price: 260,
    isVeg: false,
    healthScore: 87,
    tags: ['quick-delivery', 'high-protein', 'under-budget'],
  },
  {
    id: 'rec-7',
    name: 'Millet Khichdi Bowl',
    restaurantName: 'Satvik Meals',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop',
    rating: 4.2,
    etaMinutes: 24,
    distanceKm: 1.7,
    calories: 390,
    proteinGrams: 22,
    price: 190,
    isVeg: true,
    healthScore: 89,
    tags: ['under-budget', 'vegetarian'],
  },
  {
    id: 'rec-8',
    name: 'Grilled Chicken Salad Box',
    restaurantName: 'Lean Lunch Co.',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop',
    rating: 4.6,
    etaMinutes: 19,
    distanceKm: 1.4,
    calories: 430,
    proteinGrams: 44,
    price: 295,
    isVeg: false,
    healthScore: 93,
    tags: ['high-protein', 'quick-delivery', 'under-budget'],
  },
];

export const MOCK_INSIGHTS: SmartInsight[] = [
  { id: 'ins-1', text: "You're averaging 27g more protein this week." },
  { id: 'ins-2', text: "You're ₹420 under budget this week." },
  { id: 'ins-3', text: 'You order from Green Bowl 3x/week.' },
  { id: 'ins-4', text: 'Tuesdays are your healthiest day.' },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: '7 Day Protein Streak',
    gradient: 'from-amber-500/20 to-orange-600/20',
  },
  {
    id: 'ach-2',
    title: 'Stayed under budget for 5 days',
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'ach-3',
    title: 'Ordered healthy 10 times',
    gradient: 'from-green-500/20 to-emerald-600/20',
  },
  {
    id: 'ach-4',
    title: 'Hit protein goal yesterday',
    gradient: 'from-yellow-500/20 to-amber-600/20',
  },
];

export const MOCK_WEEKLY_MEAL_PLAN: WeeklyMealPlanDay[] = [
  {
    day: 'Monday',
    date: 'Jun 30',
    breakfast: 'Oats & Berries',
    lunch: 'Chicken Salad',
    dinner: 'Dal & Roti',
    proteinGrams: 140,
    budget: 560,
  },
  {
    day: 'Tuesday',
    date: 'Jul 1',
    breakfast: 'Egg White Omelette',
    lunch: 'Quinoa Bowl',
    dinner: 'Grilled Fish',
    proteinGrams: 155,
    budget: 610,
  },
  {
    day: 'Wednesday',
    date: 'Jul 2',
    breakfast: 'Smoothie Bowl',
    lunch: 'Paneer Wrap',
    dinner: 'Veg Stir Fry',
    proteinGrams: 132,
    budget: 480,
  },
  {
    day: 'Thursday',
    date: 'Jul 3',
    breakfast: 'Greek Yogurt',
    lunch: 'Burrito Bowl',
    dinner: 'Tandoori Chicken',
    proteinGrams: 148,
    budget: 590,
  },
  {
    day: 'Friday',
    date: 'Jul 4',
    breakfast: 'Protein Pancakes',
    lunch: 'Sushi Box',
    dinner: 'Steak & Veggies',
    proteinGrams: 160,
    budget: 640,
  },
  {
    day: 'Saturday',
    date: 'Jul 5',
    isToday: true,
    breakfast: 'Greek Yogurt Bowl',
    lunch: 'Grilled Chicken',
    dinner: 'Paneer Tikka',
    proteinGrams: 92,
    budget: 340,
  },
  {
    day: 'Sunday',
    date: 'Jul 6',
    breakfast: 'Avocado Toast',
    lunch: 'Buddha Bowl',
    dinner: 'Soup & Salad',
    proteinGrams: 0,
    budget: 0,
  },
];
